# Generated by Django 2.2.6 on 2021-07-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210709_1245'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_list',
        ),
    ]
