# Generated by Django 2.2.6 on 2021-07-13 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20210712_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Картинка аватара')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL, verbose_name='Аватар Пользователя')),
            ],
            options={
                'verbose_name': 'Дата рождения пользователя',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
