# Generated by Django 2.2.6 on 2021-07-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователя'},
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='author',
            new_name='user',
        ),
    ]
