# Generated by Django 2.2.6 on 2021-07-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210713_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='author',
        ),
    ]
