# Generated by Django 2.2.6 on 2021-07-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210713_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='author',
            new_name='user',
        ),
    ]
