# Generated by Django 2.2.6 on 2021-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210715_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='city',
            field=models.CharField(blank=True, default='Москва', max_length=200, verbose_name='Город проживания'),
        ),
    ]
