# Generated by Django 2.2.6 on 2021-07-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_avatar_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='city',
            field=models.CharField(blank=True, default='Москва', max_length=30, verbose_name='Город проживания'),
        ),
    ]
