# Generated by Django 2.2.6 on 2021-07-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210716_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='last_name',
        ),
    ]
